on:
  workflow_dispatch:
    inputs:
      directorio:
        description: 'Agrega la ruta del directorio con /'
        default: 'dir/dir/example/'
        required: false
        type: string
      archivos:
        description: 'Agrega los ficheros o el comodin'
        default: '*'
        required: false
        type: string

jobs:
  print-path:
    runs-on: ubuntu-latest

    steps:
      - name: Imprime la ruta dada por el usuario
        run: echo La ruta a ejecutar es ${{ inputs.directorio }} ${{ inputs.archivos }}