on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Agrega la ruta del fichero'
        default: 'dir/dir/example.cs'
        required: false
        type: string

jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Imprime la ruta dada por el usuario
        run: echo The username is ${{ inputs.username }}