name: Merge Tag on PR
on: [workflow_dispatch]
jobs:
  sql-review:
    runs-on: ubuntu-latest
    name: SQL Review
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2
      - name: 'Tag ARMTemplate'
        run: |
            commit=$(git rev-parse HEAD)
            echo $commit
            echo 'Hello'