name: Merge Tag on PR
on: [workflow_dispatch]
jobs:
  sql-review:
    runs-on: ubuntu-latest
    name: SQL Review
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2
      - name: 'Tag ARMTemplate'
        run: |
            commit=$(git rev-parse HEAD)
            tag=$(git describe --tags `git rev-list --tags --max-count=1`)
            echo $commit

            if [ -z "$t" ]
            then
                log=$(git log --pretty=oneline)
                t=0.0.0
            else
                log=$(git log $t..HEAD --pretty=oneline)
            fi

            echo $tag