name: Merge Tag on PR
on: [pull_request]
jobs:
  sql-review:
    runs-on: ubuntu-latest
    name: SQL Review
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2
      - name: 'Tag ARMTemplate'
        run: |
            git rev-parse HEAD