name: SQL

on:
  push:

jobs:
  validate-sql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate SQL
        uses: zlepper/mssql-validator
        with:
          pattern: 'scripts/**/*.sql'