on: [pull_request]

jobs:
  sql-review:
    runs-on: ubuntu-latest
    name: SQL Review
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2
      - name: 'sqlfluff y reviewdog' 
        uses: yu-iskw/action-sqlfluff@v3
        id: lint-sql
        with:
          override-file-path: ./sql-review-override.yml
          database-type: Snowflake
          file-pattern: ^develop/scripts/.*\.sql$