name: sqlfluff with reviewdog
on:
  pull_request:
jobs:
  test-check:
    name: runner / sqlfluff (github-check)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: yu-iskw/action-sqlfluff@v3
        id: lint-sql
        with:
          github_token: ${{ secrets.github_token }}
          level: error
          reporter: github-pr-review
          fail_on_error: true
          sqlfluff_version: "1.4.5"
          sqlfluff_command: "fix"
          rules: -rules PRS
          config: "${{ github.workspace }}/.sqlfluff"
          paths: '${{ github.workspace }}/develop/postgres'
          dialect: 'tsql'
          
      - name: 'Show outputs (Optional)'
        shell: bash
        run: |
          echo '${{ steps.lint-sql.outputs.sqlfluff-results }}' | jq -r '.'
          echo '${{ steps.lint-sql.outputs.sqlfluff-results-rdjson }}' | jq -r '.'
